DELETE http://localhost:3003/api/blogs/60e08ea6a42edb2bfa2d97c7
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYwZGY4MDExY2QwM2FiMjZmNDU3MzJkZSIsImlhdCI6MTYyNTUwNzIwMywiZXhwIjoxNjI1NTEwODAzfQ.pNKmLfJKYkqidEb6Gi9lAmw0hdf_hxHVABVGz1YP0Dg
