DELETE http://localhost:3003/api/blogs/60e03851472d982aa160c427
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxvdmVsYWNlIiwiaWQiOiI2MGUzMmMyZGIyNDAwZjMwZDMwYThjMGEiLCJpYXQiOjE2MjU1MTAzNzcsImV4cCI6MTYyNTUxMzk3N30.rQdu8lkeLBtN9TVRSh9ULR02l6bNdSueACTwHStqwkU
