POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYwZGY4MDExY2QwM2FiMjZmNDU3MzJkZSIsImlhdCI6MTYyNTUxMDI3MiwiZXhwIjoxNjI1NTEzODcyfQ.wbh7PblmxIkuYmRDl4gngc318RiS-nzu6SGj6g6wejU

{
  "title": "MongoDB is web scale",
  "author": "gar1t",
  "url": "http://www.mongodb-is-web-scale.com/"
}